CHANGELOG.md, pom.xml, src/main/java/com/github/victools/jsonschema/generator/FieldScope.java, src/main/java/com/github/victools/jsonschema/generator/MemberScope.java, src/main/java/com/github/victools/jsonschema/generator/MethodScope.java, src/test/java/com/github/victools/jsonschema/generator/FieldScopeTest.java, src/test/java/com/github/victools/jsonschema/generator/MethodScopeTest.java, src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java, src/test/resources/com/github/victools/jsonschema/generator/testclass1-FULL_DOCUMENTATION.json, src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION.json
Introducing convenience function for common concern in modules:
- `MemberScope.getAnnotationConsideringFieldAndGetter(Class)`
=> Annotation convenience function

CHANGELOG.md, README.md, jsonschema-generator/README.md, jsonschema-generator/pom.xml, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaKeyword.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaVersion.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorAllOfCleanUpTest.java, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_6.json, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/custom-property-definition-DRAFT_6.json, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/multiple-definitions-one-type-DRAFT_6.json, jsonschema-module-javax-validation/src/main/java/com/github/victools/jsonschema/module/javax/validation/JavaxValidationOption.java, pom.xml
The differences between Draft 6 and 7 are not that big – might as well also support Draft 6 then.
=> Add official support for Draft 6

CHANGELOG.md, jsonschema-generator/pom.xml, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass2-array.json, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION.json, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testenum-FULL_DOCUMENTATION-default.json, jsonschema-module-jackson/pom.xml, jsonschema-module-javax-validation/pom.xml, jsonschema-module-swagger-1.5/pom.xml, pom.xml
As per #76, introducing new `Option.DEFINITION_FOR_MAIN_SCHEMA`.
=> Allow moving main/target schema to definitions/$defs

jsonschema-maven-plugin/README.md, jsonschema-maven-plugin/pom.xml, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/TestPackage/TestClassA.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/TestPackage/TestClassB.java, jsonschema-maven-plugin/src/test/resources/error-test-cases/ClassNotFound-pom.xml, jsonschema-maven-plugin/src/test/resources/error-test-cases/UnknownGeneratorPreset-pom.xml, jsonschema-maven-plugin/src/test/resources/error-test-cases/UnknownModule-pom.xml, jsonschema-maven-plugin/src/test/resources/error-test-cases/UnknownSchemaVersion-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/Complete-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/DefaultConfig-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/FileNamePattern-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/JacksonModule-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/PackageName-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/SchemaFileName-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/SchemaVersion-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/TestClassA-reference.json, jsonschema-maven-plugin/src/test/resources/reference-test-cases/TestClassB-reference.json, jsonschema-maven-plugin/src/test/resources/reference-test-cases/TwoClasses-pom.xml
Finally discovered the **nasty** flag on SubTypesScanner. Package based generation now also works.
I have not looked at the dependencies in the pom too much.
=> 80 generating schemas for multiple classes

jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java, jsonschema-maven-plugin/src/test/resources/error-test-cases/EmptyPackage-pom.xml
Hi Carsten,
A small improvement in trying to get a better understandable error message.
Please review, because the code is a little fishy. Maybe we should keep it to a generic error only.
I leave that up to you.
Regards,
Jan
=> - Improved error message in case an empty or incorrect package is given.

CHANGELOG.md, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MemberScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/PropertySortUtils.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/TypeContextFactory.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-JAVA_OBJECT-methodattributes.json, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
Introducing `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS` to address feature request mentioned in GH-115.
=> feat: new option to derive fields from methods

CHANGELOG.md, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/AttributeCollectorTest.java, jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/CustomEnumDefinitionProviderTest.java
Implementing new `Option` for the feature requested in #142.
=> feat: introduce Option.ENUM_KEYWORD_FOR_SINGLE_VALUES

CHANGELOG.md, README.md, jsonschema-maven-plugin/README.md, jsonschema-maven-plugin/pom.xml, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java, jsonschema-maven-plugin/src/test/resources/reference-test-cases/JakartaValidationModule-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/JakartaValidationModule-reference.json, jsonschema-module-jakarta-validation/README.md, jsonschema-module-jakarta-validation/pom.xml, jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java, jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationOption.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/IntegrationTest.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModuleTest.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/TestType.java, jsonschema-module-jakarta-validation/src/test/resources/com/github/victools/jsonschema/module/jakarta/validation/integration-test-result.json, pom.xml, slate-docs/source/includes/_jakarta-validation-module.md, slate-docs/source/index.html.md
This PR includes the initial implementation of #156 and some slight adjustments in the documentation referring to the new `JakartaValidationModule`.
=> Jakarta validation module

CHANGELOG.md, jsonschema-module-jackson/README.md, jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java, jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonOption.java, jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JacksonModuleTest.java, pom.xml, slate-docs/source/includes/_jackson-module.md
Provided PR #163 + some small documentation adjustments.
=> feat: add JacksonOption.RESPECT_JSONPROPERTY_REQUIRED

CHANGELOG.md, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModule.java
=> feat: support URI as simple type

CHANGELOG.md, jsonschema-maven-plugin/README.md, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java, pom.xml, slate-docs/source/includes/_main-generator.md, slate-docs/source/includes/_maven-plugin.md
=> fix: Enable usage of maven plugin with jdk11

CHANGELOG.md, jsonschema-generator-bom/pom.xml, pom.xml
=> chore: add bom

CHANGELOG.md, jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java, jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IgnorePropertyTest.java
=> fix: jackson module correctly consider `@JsonIgnoreProperites`

README.md
Using toPrettyString() will provide a nicer output for the first run of the program :)
=> toPrettyString README.md

CHANGELOG.md, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/InlineSchemaModule.java, jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
=> fix: ensure thread safety

jsonschema-maven-plugin/README.md, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
Fixes #272 
(hopefully, could not test, as the maven plugin tests are broken on Windows (see #274 ))
=> Added parameter to continue build if no classes are found

CHANGELOG.md, jsonschema-generator-parent/pom.xml, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java, jsonschema-maven-plugin/src/test/resources/error-test-cases/ClassNotFound-dontFailIfNoClassesMatch-pom.xml, slate-docs/source/includes/_maven-plugin.md
Fixes #274 (by attempting to ignore the end-of-line differences as pointed out as likely culprit).
Completing the documentation for #273.
=> chore(docs): Mention new maven plugin param

CHANGELOG.md, jsonschema-generator-parent/pom.xml, jsonschema-maven-plugin/README.md, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/AnnotationParameter.java, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/ClasspathType.java, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/ClasspathTypeTest.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/annotations/AnotherTestAnnotation.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/annotations/TestAnnotation.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/testpackage/TestClassA.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/testpackage/TestClassB.java, jsonschema-maven-plugin/src/test/resources/reference-test-cases/AnnotationMixed-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/AnnotationMulti-pom.xml, jsonschema-maven-plugin/src/test/resources/reference-test-cases/AnnotationSingle-pom.xml, slate-docs/source/includes/_maven-plugin.md
merging changes from #276 with minor clean-ups and some further entries in the documentation
=> Maven plugin supporting classpath parameter and selection by type annotation

CHANGELOG.md, jsonschema-module-jakarta-validation/README.md, jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/IntegrationTest.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModuleTest.java, jsonschema-module-jakarta-validation/src/test/resources/com/github/victools/jsonschema/module/jakarta/validation/integration-test-result.json, slate-docs/source/includes/_jakarta-validation-module.md
=> feat: jakarta minProperties/maxProperties for Map types

.github/workflows/maven.yml, jsonschema-generator-parent/pom.xml, jsonschema-generator/pom.xml, jsonschema-module-jackson/pom.xml, jsonschema-module-jakarta-validation/pom.xml, jsonschema-module-javax-validation/pom.xml, jsonschema-module-swagger-1.5/pom.xml, jsonschema-module-swagger-2/pom.xml
* Applies ModiTect plugin with custom module names
* Bumps build to Java 11 yet bytecode remains Java 8 compatible
=> feat: Add explicit module descriptors

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/GroupedAnnotationExample.java, jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java, jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/GroupedAnnotationExample-result.json, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtilsTest.java, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json, jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json
- adding unit tests to prove current/correct behavior
- add another (unrelated) example
=> fix: strict type info should be distinct

CHANGELOG.md, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MemberScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java, jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/IntegrationTest.java, jsonschema-module-javax-validation/src/main/java/com/github/victools/jsonschema/module/javax/validation/JavaxValidationModule.java, jsonschema-module-javax-validation/src/test/java/com/github/victools/jsonschema/module/javax/validation/IntegrationTest.java
- add generic support
- utilise new generic meta annotation support in `JakartaValidationModule`
- utilise new generic meta annotation support in `JavaxValidationModule`
=> feat: Support meta annotations (jakarta, javax)

CHANGELOG.md, jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/AnnotationInheritanceExample.java, jsonschema-generator-parent/pom.xml, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilder.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/DefinitionKey.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/PropertySortUtils.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/TypeContextFactory.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/AdditionalPropertiesModule.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/EnumModule.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModule.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaBuilderTest.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/AttributeCollectorTest.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImplTest.java, jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/IntegrationTest.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModuleTest.java, jsonschema-module-jakarta-validation/src/test/resources/com/github/victools/jsonschema/module/jakarta/validation/integration-test-result.json, jsonschema-module-javax-validation/src/main/java/com/github/victools/jsonschema/module/javax/validation/JavaxValidationModule.java, jsonschema-module-javax-validation/src/test/java/com/github/victools/jsonschema/module/javax/validation/IntegrationTest.java, jsonschema-module-javax-validation/src/test/java/com/github/victools/jsonschema/module/javax/validation/JavaxValidationModuleTest.java, jsonschema-module-javax-validation/src/test/resources/com/github/victools/jsonschema/module/javax/validation/integration-test-result.json
Resolving #297 and replacing #299.
=> feat: Support inheritance for validation constraint annotations

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/JacksonDescriptionAsTitleExample.java, jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java, jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/JacksonDescriptionAsTitleExample-result.json
=> chore(example): Create example applying jackson descriptions as titles

CHANGELOG.md, jsonschema-module-jackson/README.md, jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java, jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonUnwrappedDefinitionProvider.java, jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IntegrationTest.java, jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JacksonModuleTest.java, jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/integration-test-result.json, slate-docs/source/includes/_jackson-module.md
=> feat: Support jackson @JsonUnwrapped annotation

CHANGELOG.md, jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java, jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java, jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-TestClass.json
=> fix: swagger-2-module multipleOf rounding error

CHANGELOG.md, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/FieldScopeTest.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/MethodScopeTest.java
=> feat: support boolean getter with method name matching field name

CHANGELOG.md, jsonschema-generator-parent/pom.xml, jsonschema-module-swagger-2/README.md, jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java, jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java, slate-docs/source/includes/_swagger-2-module.md
=> feat: swagger2 module - add support for @Schema.requiredMode

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/EnumMapExample.java, jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java, jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/EnumMapExample-result.json
Demonstrate dynamic object schema creation from map with enum keys, as requested on #376.
=> Add enum map example

CHANGELOG.md, jsonschema-generator-parent/pom.xml, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/ClasspathType.java, jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/TestClass.java, jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/TestModule.java, jsonschema-maven-plugin/src/test/resources/reference-test-cases/Complete-reference.json, jsonschema-maven-plugin/src/test/resources/reference-test-cases/JacksonModule-reference.json, slate-docs/source/includes/_maven-plugin.md
Closes #384: Adding documentation after #388 was already merged to provide the feature itself.
Resolves #383: Enable loading custom Module in Maven plugin from test package.
=> feat: Maven plugin enhancements

jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
=> chore: refactor for improved code health

CHANGELOG.md, jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/InheritanceRefExample.java, jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java, jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/InheritanceRefExample-result.json, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MemberScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/MemberCollectionContextImpl.java, jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/AbstractTypeAwareTest.java, jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/AbstractTypeAwareTest.java, jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/TestType.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/TestType.java, jsonschema-module-javax-validation/src/test/java/com/github/victools/jsonschema/module/javax/validation/TestType.java, jsonschema-module-swagger-1.5/src/test/java/com/github/victools/jsonschema/module/swagger15/TestType.java
=> feat: enable differentiating members declared by super types

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/TargetTypeOverrideExample.java, jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java, jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/TargetTypeOverrideExample-result.json
=> chore: add example for target type override

CHANGELOG.md, jsonschema-examples/pom.xml, jsonschema-generator-bom/pom.xml, jsonschema-generator-parent/pom.xml, jsonschema-generator/pom.xml, jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java, jsonschema-maven-plugin/pom.xml, jsonschema-module-jackson/pom.xml, jsonschema-module-jakarta-validation/README.md, jsonschema-module-jakarta-validation/pom.xml, jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/IntegrationTest.java, jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModuleTest.java, jsonschema-module-jakarta-validation/src/test/resources/com/github/victools/jsonschema/module/jakarta/validation/integration-test-result.json, jsonschema-module-javax-validation/pom.xml, jsonschema-module-swagger-1.5/pom.xml, jsonschema-module-swagger-2/pom.xml, pom.xml, slate-docs/source/includes/_jakarta-validation-module.md
Updating changelog and increase minor version for changes introduced in #456.
=> Support Jakarta @AssertTrue/@AssertFalse annotations

CHANGELOG.md, jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java, jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java, jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-TestClass.json
=> fix: Swagger2Module treat as nullable by default
