CHANGELOG.md
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java

Underlying type resolution allows for a parameterized type to passed-in together with its type parameters.
This is simply being exposed here on the main `SchemaGenerator.generateSchema()` method, while still being backward-compatible, i.e. if no type parameters are provided for a given parameterized type, only the lower bounds of the respective type parameters will be considered (if there are any).

Allow passing type parameters on generateSchema

---

.gitignore
pom.xml
src/main/java/com/github/victools/jsonschema/generator/SchemaConstants.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPart.java
src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java

feat: add "default" value properties
feat: add "required" properties
feat: add resolve metadata
conf: add more rules in gitignore

Add new Json schema properties

---

CHANGELOG.md
pom.xml

Suggested dependency upgrade to fix the following security alerts:
- [CVE-2019-14540](https://nvd.nist.gov/vuln/detail/CVE-2019-14540)
- [CVE-2019-16335](https://nvd.nist.gov/vuln/detail/CVE-2019-16335)
Both are categorised as "Polymorphic Typing issues" with "critical severity".

Update jackson dependency version

---

CHANGELOG.md
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java
src/test/resources/com/github/victools/jsonschema/generator/testclass1-PLAIN_JSON-attributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-attributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-attributes.json

Fixes issue reported #15 that the majority of collected attributes are ignored for container types (i.e. arrays and collections).
As it turns out, the bug was already visible in the existing tests – I just didn't realize it. 😞

fix: apply collected attributes also to container types

---

CHANGELOG.md
checkstyle.xml
pom.xml
src/main/java/com/github/victools/jsonschema/generator/CustomDefinitionProviderV2.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerationContext.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilder.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContext.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
src/main/java/com/github/victools/jsonschema/generator/impl/module/ConstantValueModule.java
src/test/java/com/github/victools/jsonschema/generator/AbstractTypeAwareTest.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImplTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImplTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/module/EnumModuleTest.java

Main purpose of these changes:
- Allowing a `CustomDefinitionProviderV2` (replacing `CustomDefinitionProvider`) to hand-off the generation of parts of the custom definition to the normal generator instance
To make this manageable, some logic was moved out of the main `SchemaGenerator` class into the `SchemaGenerationContextImpl` class (renamed from `SchemaGenerationContext` to avoid name conflicts with the newly introduced `SchemaGenerationContext` interface).
The tests were kept on the `SchemaGenerator` level to reduce the amount of work necessary here and to show that the previous behavior remained unchanged.

Extend custom definitions

---

CHANGELOG.md
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java
src/test/resources/com/github/victools/jsonschema/generator/testclass1-FULL_DOCUMENTATION.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION-attributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-attributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-attributes.json

As reported in #19, some validators like https://jsonschemalint.com/#!/version/draft-07/markup/json report generated schemas as valid when there are white-spaces in the values provided to `$ref`.
This affects two kinds of references:
- In case of generic types with more than one type parameter, e.g. `Map<String, String>`.
- When specifically handling `null`-able definitions, which get the `" (nullable)"` suffix.
----
Simple fix here: remove any whitespaces in the definition keys, consequently not using those invalid keys as `$ref`.
To show-case the changed behavior, the existing tests for the schema generation can be extended to include a generic with two parameters. Nullable examples are already present.

fix: avoid white-spaces in definition keys

---

CHANGELOG.md
src/main/java/com/github/victools/jsonschema/generator/Option.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilder.java
src/main/java/com/github/victools/jsonschema/generator/impl/module/EnumModule.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/module/EnumModuleTest.java
src/test/resources/com/github/victools/jsonschema/generator/testenum-FULL_DOCUMENTATION-default.json
src/test/resources/com/github/victools/jsonschema/generator/testenum-PLAIN_JSON-default.json
src/test/resources/com/github/victools/jsonschema/generator/testenum-PLAIN_JSON-viaToString.json

Also introducing explicit overrides between related options.
While the new `Option.FLATTENED_ENUMS_FROM_TOSTRING` is not being added to any existing `OptionPreset` by default – to ensure backward-compatibility – it is treated as the one with highest priority of the three enum related options:
- `Option.SIMPLIFIED_ENUMS`
- `Option.FLATTENED_ENUMS`
- `Option.FLATTENED_ENUMS_FROM_TOSTRING`
That means, the other options don't need to be explicitly disabled to use the new `Option`.

Introduce new Option.FLATTENED_ENUMS_FROM_TOSTRING

---

src/main/java/com/github/victools/jsonschema/generator/impl/module/ConstantValueModule.java

There is no functional implication here, it is purely about not using a deprecated/removed method anymore.
Compilation under older JDK versions should therefore also not be affected.

Allow compilation under JDK11

---

CHANGELOG.md
README.md
src/main/java/com/github/victools/jsonschema/generator/TypeContext.java
src/main/java/com/github/victools/jsonschema/generator/TypeScope.java
src/main/java/com/github/victools/jsonschema/generator/impl/module/FlattenedOptionalModule.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java

The goal is to enable simpler configurations by already taking care of some edge cases like a generic type (e.g. Map<K, V>` being used without type parameters (i.e. as raw `Map`), by simply returning `Object` as lower boundary then.
For simplicity's sake, the actual look-up of boundaries of the generic type itself is being left-out here, especially since the handling of union types is not that straightforward.

Offer safer/convenient type parameter look-up

---

CHANGELOG.md
README.md
src/main/java/com/github/victools/jsonschema/generator/SchemaConstants.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPart.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorTypeConfigPart.java
src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java
src/test/resources/com/github/victools/jsonschema/generator/testclass1-FULL_DOCUMENTATION-typeattributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION-typeattributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json

In the scope of the support for `additionalProperties` (#22), the discussion touched upon the related `patternProperties`.
As they are very similar, adding the support for `patternProperties` here is not much trouble.

Support configuration for patternProperties

---

CHANGELOG.md
README.md
src/main/java/com/github/victools/jsonschema/generator/Option.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilder.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
src/main/java/com/github/victools/jsonschema/generator/impl/module/AdditionalPropertiesModule.java
src/main/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModule.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImplTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModuleTest.java
src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json

Changes made in the interest of making the usage of `additionalProperties`/`patternProperties` more convenient (as per #22):
- Specifically omit both newly supported keywords in case of the custom definitions for simple types (i.e. the non-`object` ones as well as the base `Object.class`).
- Introduce new `Option.FORBIDDEN_ADDITIONAL_PROPERTIES_BY_DEFAULT` that applies to all definitions except for the specifically ones mentioned above and anything with `TypeScope.isContainerType()` being `true`.

feat: default for additional/patternProperties

---

src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
src/test/java/com/github/victools/jsonschema/generator/impl/AttributeCollectorTest.java

Avoiding `{ "type": "object" }` to be included for unknown `additionalProperties` or `patternProperties` as that might also represent non-`object` types (like a number/string/boolean).
Relates to #28/#31/#32.

fix: treat Object.class as property wildcard

---

CHANGELOG.md
src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
src/main/java/com/github/victools/jsonschema/generator/impl/module/EnumModule.java
src/main/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModule.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/AttributeCollectorTest.java
src/test/resources/com/github/victools/jsonschema/generator/testclass2-array.json

The `Object.class` is currently represented by the following schema by default:
```javascript
{
"type": "object"
}
```
However, that means any kind of element (e.g. "string", "number", "array") would fail the validation against this schema, even though from a Java perspective everything is an `Object`. Therefore changing this here now to simply omit the `"type"` for an otherwise unspecified `Object`.
----
Additionally, some collected attributes may not be valid in combination with the declared `"type"` in a sub-schema.
For now, only in the `SchemaGeneratorConfigBuilder.forTypesInGeneral()` the collection of some attributes is being skipped, if the existing `"type"` makes them invalid:
- `"string"` attributes are only collected if that `"type"` is declared (or no `"type"` at all)
- …

Improved object handling

---

CHANGELOG.md
src/main/java/com/github/victools/jsonschema/generator/Option.java
src/main/java/com/github/victools/jsonschema/generator/OptionPreset.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json

- Removing unnecessary `allOf` elements when all contained attributes are distinct (i.e. can be merged into one schema without overriding each other).
- Allow co-existence of `$ref` with other attributes as per Draft 2019-09 (GH-14) but preserving previous behavior for Draft 7, where officially any attributes beside `$ref` were to be ignored.
- Introduce new `Option.ALLOF_CLEANUP_AT_THE_END` that is included in all standard `OptionPreset`s but can be turned off if desired (e.g. to preserve manually added `allOf` elements even though they are not necessary or in order to reduce overall schema generation time).

feat: introduce clean-up of unnecessary allOf elements

---

CHANGELOG.md
checkstyle.xml
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
src/main/java/com/github/victools/jsonschema/generator/TypeContext.java
src/main/java/com/github/victools/jsonschema/generator/impl/DefinitionKey.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPartTest.java
src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorCustomDefinitionsTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/AttributeCollectorTest.java
src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImplTest.java
src/test/resources/com/github/victools/jsonschema/generator/multiple-definitions-one-type-DRAFT_2019_09.json
src/test/resources/com/github/victools/jsonschema/generator/multiple-definitions-one-type-DRAFT_7.json

There was a limitation in the way non-inline definitions were remembered, which resulted in only one definition to be saved per type. This meant that using `SchemaGenerationContext.createStandardDefinitionReference()` in a custom definition resolver did not yield the expected results when the surrounding custom definition was not marked as to be "inline".
As a side-effect of this fix, another limitation is also being lifted: when multiple encountered types had the same class name (e.g. a "Vehicle" interface and a "Vehicle" class), the same issue occurred: only one entry was added to the schema's `definitions`.
Now, the different definitions are properly detected and added separately (with a numeric index appended to their key in the `definitions`, but only if necessary).
I.e. the …

fix: handle multiple definitions with same name

---

CHANGELOG.md
README.md
src/main/java/com/github/victools/jsonschema/generator/CustomDefinition.java
src/main/java/com/github/victools/jsonschema/generator/CustomPropertyDefinition.java
src/main/java/com/github/victools/jsonschema/generator/CustomPropertyDefinitionProvider.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGenerationContext.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPart.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImplTest.java

In some circumstances, there may be the need to assign custom definitions in the scope of a particular property, e.g. when considering per-property annotations that override the per-type behavior.

Custom Definitions for fields/methods

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/InlineSchemaModule.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json

Introducing new `Option.INLINE_ALL_SCHEMAS`. This resolves #59 and follows the approach presented by @opbokel on that issue.
Throws an `IllegalArgumentException` when encountering a circular reference (instead of running into endless loops).

Inline all the things

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/InstanceAttributeOverrideV2.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGenerationContext.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorGeneralConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SubtypeResolver.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeAttributeOverrideV2.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPartTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImplTest.java

- Offering also `SchemaGenerationContext.createStandardDefinition(FieldScope, CustomPropertyDefinitionProvider)`
- Offering also `SchemaGenerationContext.createStandardDefinition(MethodScope, CustomPropertyDefinitionProvider)`
- Alternative `SchemaGenerationConfigPart.withInstanceAttributeOverride(InstanceAttributeOverrideV2)` with access to `SchemaGenerationContext`
- Providing access to the `SchemaGenerationContext` when invoking `TypeAttributeOverrideV2` (potentially BREAKING change in case of lambda usage)

Provide generation context to attribute overrides

---

README.md
jsonschema-maven-plugin/README.md
jsonschema-maven-plugin/pom.xml
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/GeneratorOptions.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/StandardOptionPreset.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java
pom.xml

@JanLabrie I've made a couple small changes to the pending Maven Plugin.
Since it is your creation, I'd appreciate if you could have a look – I don't want to "just merge" it without asking.
1. renamed goal to `generate` to make the command-line call nicer. that is now `jsonschema:generate` (unless you think `jsonschema:generate-schema` is better?)
2. update pom to avoid unnecessary plugin management (that is being taken care of by the parent pom already)
3. some small fixes in README
4. align maven plugin code with existing codebase (import order + using `this.` prefix)
5. getting rid of the explicit `ClassLoader` code by adding dependency scope on `@Mojo` annotation
6. stricter configuration of `SchemaVersion` and `OptionPreset` through enums (therefore no need to specifically map values …

Maven Plugin cleanups

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorGeneralConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/PropertySortUtils.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/PropertySortUtilsTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-FULL_DOCUMENTATION-typeattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION-typeattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json
jsonschema-module-javax-validation/src/test/resources/com/github/victools/jsonschema/module/javax/validation/integration-test-result.json

By default, an object's properties are being sorted alphabetically by their names – with fields being listed first followed by the methods (depending on what is being included).
With this change, it is possible to alter the sorting algorithm.
Unfortunately, the possibility to preserve the declaration order requested in GH-92 depends on the specific compiler being used – but at least, this way you can apply any sorting you want, e.g. based on the Jackson `@JsonPropertyOrder` or similar annotations if you so chose.

Configuration of Property Order

---

CHANGELOG.md
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/PropertySortUtilsTest.java
jsonschema-module-jackson/README.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonOption.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonPropertySorter.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JacksonModuleTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonPropertySorterTest.java

Enable sorting of an object's properties based on `@JsonPropertyOrder` annotations.

Respect @JsonPropertyOrder annotation

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/LazyValue.java

Slight performance improvement:
- Cache looked-up getter in `FieldScope.findGetter()`
- Cache looked-up field in `MethodScope.findGetterField()`

feat: cache looked up getter and field

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaKeyword.java
jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java

As requested on GH-124 by @pahujatarun25, adding `"not"` to the `SchemaKeyword` enum even though no special handling of explicit configuration is supported at this stage.
So far, this keyword was only hard-coded in the new `jsonschema-module-swagger-2` where the `"minProperties"` and `"maxProperties"` keyword had also been hard-coded. To be consistent, those two are added to the central `SchemaKeyword` enum as well.
This is no behaviour change and purely convenience for users trying to avoid hard-coding on their side by using the `SchemaKeyword` enum (which is it's secondary purpose - the main purpose being the transparent support of keywords being renamed from one JSON Schema Draft to another, e.g `"id"` vs. `"$id"`).

feat: extend keyword enum

---

CHANGELOG.md
checkstyle.xml
jsonschema-maven-plugin/README.md
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/GlobHandler.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/PotentialSchemaClass.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/GlobHandlerTest.java
jsonschema-maven-plugin/src/test/resources/reference-test-cases/SchemaFileName-pom.xml
jsonschema-maven-plugin/src/test/resources/reference-test-cases/TwoClasses-pom.xml

Implementing feature requested in GH-104:
- Adding support for including classes via glob patterns in `<classNames>` and `<packageNames>` (in addition to absolute paths)
- Adding support for excluding classes via absolute paths or glob patterns in new `<excludeClassNames>`
- Avoid generating the same schema multiple times if there are overlaps between entries in `<classNames>` and/or `<packageNames>`.
The logic around converting a glob into a regular expression is rather complicated, but the resulting configuration is quite straightforward.
It is backward compatible with regards to the absolute paths including dots (`.´) as package separators.
@JanLabrie what do you think?

feat: maven plugin supporting globs and exclusions

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModule.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorSimpleTypesTest.java

- Adding new `Option.EXTRA_OPEN_API_FORMAT_VALUES`
- When enabled, some extra `"format"` values are being included for certain fixed types
- Extending unit tests to cover the `Option.ADDITIONAL_FIXED_TYPES`

feat: support extra OpenAPI format values

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MemberScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-javax-validation/src/main/java/com/github/victools/jsonschema/module/javax/validation/JavaxValidationModule.java
jsonschema-module-javax-validation/src/test/java/com/github/victools/jsonschema/module/javax/validation/IntegrationTest.java
jsonschema-module-javax-validation/src/test/resources/com/github/victools/jsonschema/module/javax/validation/integration-test-result.json
jsonschema-module-swagger-1.5/src/main/java/com/github/victools/jsonschema/module/swagger15/SwaggerModule.java

Closing #138.
Similar to #60, this is limited to the top-level.
- `Optional<@Size(min = 5) String>` will be picked up
- `List<Optional<@Size(min = 5) String>>` will **not** be picked up
While this is added as a general feature, it only results in an actual feature change in the `jsonschema-module-javax-validation`.

Support inline optional param annotation

---

jsonschema-maven-plugin/README.md
jsonschema-maven-plugin/pom.xml
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java
jsonschema-maven-plugin/src/test/resources/reference-test-cases/JakartaValidationModule-pom.xml
jsonschema-maven-plugin/src/test/resources/reference-test-cases/JakartaValidationModule-reference.json
jsonschema-module-jakarta-validation/README.md
jsonschema-module-jakarta-validation/pom.xml
jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java
jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationOption.java
jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/IntegrationTest.java
jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModuleTest.java
jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/TestType.java
jsonschema-module-jakarta-validation/src/test/resources/com/github/victools/jsonschema/module/jakarta/validation/integration-test-result.json
pom.xml

A simple Java Validation clone to support Jakarta Validation. 
A more elegant way might be to support both packages in one module. Nevertheless this requires more complex dependency management in the code for class accessibility. So I decide for the cloned and repackaged code.

Support for Jakarta Validation 3.0.0 added

---

jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonOption.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JacksonModuleTest.java
slate-docs/source/includes/_jackson-module.md

This PR will hopefully add an option, JacksonOption.RESPECT_JSONPROPERTY_REQUIRED, to populate "required" json schema property according to @JsonProperty(required...) value

#162 : add JacksonOption.RESPECT_JSONPROPERTY_REQUIRED

---

CHANGELOG.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolverCustomDefinitionsTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolverLookUpTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionFromInterfaceIntegrationTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-interface-integration-test-result.json

> subtype resolution now also respects `@JsonTypeInfo` annotation on the common interface (and not just common superclass)
This addresses raised issue https://github.com/victools/jsonschema-generator/issues/185.
The assumption here is, that such a `@JsonTypeInfo` annotation is only present on either a superclass or up to one implemented interface, therefore not requiring any sophisticated logic for determining which one to take. Similarly, there is no need to toggle this extended behavior through some explicit `Option`.

feat: support jackson typeinfo annotation on interface

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaKeyword.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json
jsonschema-module-swagger-2/README.md
jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/Swagger2ModuleTest.java
jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-Foo.json
slate-docs/source/includes/_main-generator.md
slate-docs/source/includes/_swagger-2-module.md

- support `readOnly` and `writeOnly` in main `jsonschema-generator`
- implement configuration for `readOnly` and `writeOnly` in `jsonschema-module-swagger-2` based on `@Schema.accessMode` as requested in issue #193

Add support for readOnly and writeOnly keywords

---

CHANGELOG.md
jsonschema-module-jackson/README.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonOption.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JacksonModuleTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/integration-test-result.json
pom.xml
slate-docs/source/includes/_jackson-module.md

- Consider `@JsonProperty.value` override for methods
- Look-up `"description"` for methods (if included) based on `@JsonPropertyDescription`
- Consider `@JsonProperty(access = Access.READ_ONLY)` when determining whether a field/method should be marked as `readOnly`
- Consider `@JsonProperty(access = Access.WRITE_ONLY)` when determining whether a field/method should be marked as `writeOnly`
- Introduce `JacksonOption.INCLUDE_ONLY_JSONPROPERTY_ANNOTATED_METHODS` to enable easy inclusion of annotated non-getter methods (typically in combination with the general `Option.FIELDS_DERIVED_FROM_ARGUMENTFREE_METHODS` and `Option.NONSTATIC_NONVOID_NONGETTER_METHODS`)
- Ignore getter methods when their associated field is being ignored (according to various Jackson annotations)
- Ignore methods when …

Jackson module features

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilderTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorSimpleTypesTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorSubtypesTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-FULL_DOCUMENTATION-typeattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-JAVA_OBJECT-methodattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-PLAIN_JSON-fieldattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION-typeattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionFromInterfaceIntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionIntegrationTest.java
jsonschema-module-swagger-1.5/src/test/java/com/github/victools/jsonschema/module/swagger15/IntegrationTest.java
jsonschema-module-swagger-1.5/src/test/resources/com/github/victools/jsonschema/module/swagger15/integration-test-result.json
jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-TestClass.json

As pointed out in https://github.com/victools/jsonschema-generator/discussions/212, JSON Schema Validators (e.g. the "networknt/json-schema-validator") do not allow `null` values for a schema like the following:
```json
{
"type": ["string", "null"],
"enum": ["A", "B", "C"]
}
```
Instead, the schema needs to look like this:
```json
{
"anyOf": [
{
"type": "null"
},
{
"type": "string",
"enum": ["A", "B", "C"]
}
]
}
```
----
This is already working correctly when the same type is being encountered both in nullable and non-nullable form.
But if a given type only appears in nullable form, the wrong schema is being created.
----
While updating the test accordingly, I also introduced a small change to the default `ObjectMapper` instance, which is being used when no specific one is given in the …

Correctly handle nullable enums

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaVersion.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_2020_12.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/custom-property-definition-DRAFT_2020_12.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/multiple-definitions-one-type-DRAFT_2020_12.json

None of the standard keywords were changed in a relevant way, most notably:
- `items` when used for tuples are renamed to `prefixItems` – since no explicit tuple support exists, no change is needed
- `additionalItems` got renamed to `items` – since no explicit support for that keyword exists, no change is needed
- logic around `dynamicAnchor`/`dynamicRef` was altered – since no explicit support for those keywords exists, no change is needed
- support for creating a composite schema sounds interesting but is not necessary at this stage and is maybe added later (once someone asks for it or even provides a PR).

Add support for Draft 2020-12

---

jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java

When running `mvn install --threads 1C` with a project that has this plugin you get the following warnings. This change will remove those warnings:
```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] …
```

Marked SchemaGeneratorMojo as ThreadSafe

---

slate-docs/source/includes/_faq.md

spurious additional `)` character, code compiles when removed:

Fix typo in Java code snippet

---

CHANGELOG.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolverCustomDefinitionsTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionFromInterfaceIntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionIntegrationTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-integration-test-result.json
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-interface-integration-test-result.json

According to the Jackson Documentation the [JsonSubTypes.Type](http://fasterxml.github.io/jackson-annotations/javadoc/2.13/com/fasterxml/jackson/annotation/JsonSubTypes.Type.html)) values inside a `@JsonSubTypes` annotation are:
> Definition of a subtype, along with optional name(s). If no name is defined (empty Strings are ignored), class of the type will be checked for [JsonTypeName](http://fasterxml.github.io/jackson-annotations/javadoc/2.13/com/fasterxml/jackson/annotation/JsonTypeName.html) annotation; and if that is also missing or empty, a default name will be constructed by type id mechanism. Default name is usually based on class name.
I.e. it should be:
1. `@JsonSubTypes.value[].name` if present and not empty (on supertype or respective property)
2. `@JsonTypeName.name` if …

Jackson Module: subtype resolution does not look-up discriminator value correctly

---

CHANGELOG.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionIntegrationTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-integration-test-result.json

Jackson supports adding a `@JsonTypeInfo(use = JsonTypeInfo.Id.NONE)` annotation on a property, in order to avoid the "normal" wrapping/modification being applied by the combination of `@JsonTypeInfo` and `@JsonSubTypes`.
This should be supported by the `JacksonModule` accordingly.
Closes #165.

Support jackson subtype property override with JsonTypeInfo.Id.NONE

---

CHANGELOG.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonPropertySorter.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonPropertySorterTest.java

As per description on #243:
> In the super class all field index values are MAX integer. So when generating the schema it reads incorrectly the field index value from two different indexes so the values are in no way comparable.
> 
> The sub class order should completely override the super class order and the super class order in [its] entirety [should] be ignored. Super class order should only be used when the super class is the schema root entity.
Closes #243.

chore(fix): Jackson @JsonPropertyOrder should be considered only on target type

---

jsonschema-generator-parent/pom.xml

The javadoc path varies between Java 8 and 11, the Java 8 one having an
extra `jre` directory in the pathname:
Java 8:
$ /usr/lib/jvm/java-8-openjdk-amd64/bin/java \
-XshowSettings:properties -version 2>&1|grep java.home
java.home = /usr/lib/jvm/java-8-openjdk-amd64/jre
Java 11
$ /usr/lib/jvm/java-11-openjdk-amd64/bin/java \
-XshowSettings:properties -version 2>&1|grep java.home
java.home = /usr/lib/jvm/java-11-openjdk-amd64
Set javadocExecutable via Maven profiles which activate based on the JDK
version being used.
That fixes the build under Java 11 when `JAVA_HOME` is not set.

chore: fix javadoc with Java 9 and later

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/module/AdditionalPropertiesModuleTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/impl/module/additional-property-with-subtype.json

Although this was reported in the context of `additionalProperties` it is actually a general fix for the combination of the following conditions:
- A configured `SubtypeResolver` (standard/built-in or custom) returns a single subtype for some given supertype.
- The default logic for "schema inlining" is enabled (i.e., neither `Option.INLINE_ALL_SCHEMAS` nor ` Option.DEFINITIONS_FOR_ALL_OBJECTS` are  used)
- The supertype is only referenced once, i.e., gets replaced with its inline schema definition at the end of the generation process.
Closes #261.

fix: subtype resolution with single result

---

CHANGELOG.md
jsonschema-generator-bom/pom.xml
jsonschema-generator-parent/pom.xml
jsonschema-generator/pom.xml
jsonschema-maven-plugin/pom.xml
jsonschema-module-jackson/pom.xml
jsonschema-module-jakarta-validation/pom.xml
jsonschema-module-javax-validation/pom.xml
jsonschema-module-swagger-1.5/pom.xml
jsonschema-module-swagger-2/README.md
jsonschema-module-swagger-2/pom.xml
jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java
jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-Foo.json
pom.xml
slate-docs/source/includes/_swagger-2-module.md

The `@Schema.allOf` is already supported out-of-the-box by the Swagger 2.0 Module.
Now adding similar support for the `@Schema.anyOf` and `@Schema.oneOf` respectively.
Answers #265.

Swagger2 Module: Support anyOf and oneOf on fields/methods

---

CHANGELOG.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionIntegrationTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-integration-test-result.json

When the Jackson module's built-in subtype resolution encounters a `@JsonTypeInfo´ annotation with the `defaultImpl` attribute on it, then that particular subtype is not required to include the designated type property.
From a schema point of view, the assumption is, that some other properties will make it distinct from different subtypes, in order to avoid "false positives" (e.g., another subtype where the type property was forgotten). That is then the responsibility of the schema creator.
Resolves #278, where this change was suggested by @eleftherias.

feat: jackson module support @JsonTypeInfo.defaultImpl

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorSubtypesTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-ONE_SUBTYPE_INVALID.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-ONE_SUBTYPE_VALID.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-THREE_SUBTYPES.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-TWO_SUBTYPES.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-FULL_DOCUMENTATION-typeattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-JAVA_OBJECT-methodattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-PLAIN_JSON-fieldattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION-typeattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-PLAIN_JSON-fieldattributes.json
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/SubtypeResolutionSimpleIntegrationTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-simple-integration-test-result.json
jsonschema-module-swagger-1.5/src/test/resources/com/github/victools/jsonschema/module/swagger15/integration-test-result.json
jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-TestClass.json
slate-docs/source/includes/_main-generator.md

Addresses issue #280 and perhaps #283.
When encountering a member (field/method), that declares a supertype, i.e., one that has at least one explicit subtype, the current (default) behavior is to generate the member schema (considering the full field/method context, including annotations etc.) for each subtype as if that member had declared this particular subtype instead.
When this new `Option` is enabled (which it's not by default), then the subtypes are only considered as generic type, i.e., not in the context of the particular member (field/method). That allows a common definition to be produced, that can be re-used.
The side effect is, that a supertype that would otherwise always be replaced can now get its own entry in the `$defs`/`definitions`.

feat: Enable type definition for members declaring a supertype

---

CHANGELOG.md
jsonschema-generator-parent/pom.xml
jsonschema-maven-plugin/pom.xml
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/ClasspathType.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/PotentialSchemaClass.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java

Replacing outdated `reflections` library with up-to-date ´classgraph` dependency in the Maven plugin.
Side-effect: non-public types are no longer allowed as entry points for the schema generation – they are still considered within a generated schema though. Therefore this change is deemed acceptable and yields some performance improvement within the Maven plugin.

feat: maven module use classgraph instead of reflections

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MemberScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorGeneralConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorTypeConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaKeyword.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/AdditionalPropertiesModule.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaBuilderTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPartTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorCustomDefinitionsTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorSubtypesTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/TestUtils.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/AttributeCollectorTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/module/AdditionalPropertiesModuleTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModuleTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/impl/module/additional-property-with-subtype.json
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-simple-integration-test-result.json
jsonschema-module-jakarta-validation/src/test/resources/com/github/victools/jsonschema/module/jakarta/validation/integration-test-result.json
slate-docs/source/includes/_main-generator.md

1. Enabling identification of "container items" that are not necessarily `Iterable`, e.g, when looking at a `Map`'s values only.
2. Introducing enhanced definition of `additionalProperties` and `patternProperties`.
3. Utilising enhanced `additionalProperties` definition in `Option,ADDITIONAL_PROPERTIES_FROM_MAP_VALUES`
- Closes #287.
4. Introducing enhanced `allOf` clean-up to allow merging schemas with differing `additionalProperties` (made necessary by the above changes).
5. Introducing enhanced `allOf` clean-up to allow merging schemas with different `properties` subsets.
- Closes #183.

Advanced additional properties definition and improved allOf clean-up behaviour

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SubtypeResolver.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorCustomDefinitionsTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/custom-property-definition-DRAFT_2019_09.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/custom-property-definition-DRAFT_2020_12.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/custom-property-definition-DRAFT_6.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/custom-property-definition-DRAFT_7.json
jsonschema-module-jackson/README.md
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonOption.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonIdentityReferenceDefinitionProvider.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JacksonModuleTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonIdentityReferenceDefinitionProviderTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolverLookUpTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/integration-test-result.json
slate-docs/source/includes/_jackson-module.md

Closes #112.
Only considering `@JsonIdentityReference(alwaysAsId = true)` as the simpler scenario.

Support Jackson @JsonidentityReference(alwaysAsId = true) considering @JsonIdentityInfo

---

CHANGELOG.md
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java
jsonschema-maven-plugin/src/test/resources/reference-test-cases/PackageName-pom.xml

With the migration from `reflections` to `classgraph` in the last release (4.28.0), a regression was introduced in the Maven Plugin.
The exclusion of certain classes was not working anymore (assuming it was working before).
Fixing this here now and adjusting a unit test to show-case corrected behaviour.

fix: Maven Plugin Class Filtering

---

jsonschema-generator-parent/pom.xml
jsonschema-maven-plugin/pom.xml
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/GlobHandler.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/GlobHandlerTest.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/testpackage/sub/TestClassC.java

Avoid unnecessary use of `Pattern.compile(".*")` when matching with all given classes.

chore: Maven Plugin clean-up

---

CHANGELOG.md
jsonschema-generator/README.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/CustomDefinitionProviderV2.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/CustomPropertyDefinitionProvider.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/InstanceAttributeOverrideV2.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorGeneralConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorTypeConfigPart.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/StatefulConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SubtypeResolver.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeAttributeOverrideV2.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/naming/SchemaDefinitionNamingStrategy.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaBuilderTest.java
jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/ExternalRefCustomDefinitionProvider.java
jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/Swagger2ModuleTest.java
jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-Foo.json
slate-docs/source/includes/_swagger-2-module.md

- mainly supporting `@Schema(ref = "...")` attribute annotated on a type (not just a member)
- in order to properly handle multiple schemas being generated with a single generator/configuration instance, now also supporting to `resetAfterSchemaGenerationFinished()` on various configuration aspects

feat: Swagger2Module should support @Schema.ref on a type

---

CHANGELOG.md
jsonschema-examples/pom.xml
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/IfThenElseExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/SchemaGenerationExampleInterface.java
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/IfThenElseExample-result.json
jsonschema-examples/src/test/resources/logback.xml
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaBuilderTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/openapi.json
pom.xml

- adding a new test module, where various examples can be collected and used as additional integration tests
- first example: custom annotations used to generate `if`/`then`/`else` blocks in a schema

chore: Add setup for examples

---

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/ExternalRefAnnotationExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/ExternalRefPackageExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/IfThenElseExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/SchemaGenerationExampleInterface.java
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/ExternalRefAnnotationExample-result.json
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/ExternalRefPackageExample-result.json

Two more entries for the new "examples" folder:
- assigning an external `$ref` based on an annotation
- for use in Maven plugin: apply `$ref` to all types in a specific package (and its subpackages) and `$id` on the "main" schema

chore(example): Add examples for external refs

---

CHANGELOG.md
jsonschema-examples/pom.xml
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/StrictTypeInfoExample.java
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/StrictTypeInfoExample-result.json
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaKeyword.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
slate-docs/source/includes/_main-generator.md

- introduce new `Option.STRICT_TYPE_INFO` for implying the `type` of sub-schemas based on their contained attributes (note: implied "type" array always contains "null")
- extend consideration of sub-schemas for `allOf` clean-up to more recognized keywords

feat: Introduce Option.STRICT_TYPE_INFO

---

CHANGELOG.md
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/JacksonSubtypeDefinitionExample.java
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/JacksonSubtypeDefinitionExample-result.json
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonOption.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolverCustomDefinitionsTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/integration-test-result.json
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-integration-test-result.json
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/subtype-interface-integration-test-result.json

Introducing new `JacksonOption.INLINE_TRANSFORMED_SUBTYPES` in order to avoid definitions with `-1`/`-2` suffixes being generated in case of subtypes involving transformation (e.g., additional property, wrapping array, wrapping object).
To be used with care, as a recursive reference can cause a `StackOverflowError`. In some scenarios, such an error can be avoided by also enabling the `Option.DEFINITIONS_FOR_MEMBER_SUPERTYPES`.
Created in response to https://github.com/victools/jsonschema-generator/discussions/337

feat: Introduce `JacksonOption.INLINE_TRANSFORMED_SUBTYPES`

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorAllOfCleanUpTest.java

This fixes #348.
However, that doesn't resolve the fact that when you reach the affected point in the code, your generated schema may contain an error due to unresolvable type definitions (e.g., at the same time `type: object` and `type: string`).

fix: error during allOf clean-up for invalid schema

---

CHANGELOG.md
jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/Swagger2ModuleTest.java
jsonschema-module-swagger-2/src/test/resources/com/github/victools/jsonschema/module/swagger2/integration-test-result-Foo.json

Introduction support for the `@Schema(additionalProperties = ...)` annotation attribute.
- only considering it on a type definition – not on a member (i.e., field or method) as that may cause conflicts
- additional exception: when there is also an external `@Schema(ref = "...")`, the `additionalProperties` attribute is not only ignored but explicitly set to allowed (even if otherwise forbidden by default).
Closes #352.

feat: swagger-2 additionalProperties support

---

jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGenerator.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilder.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfigBuilderTest.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java

Hi, I put together this rough PR based on our discussion in #384. 
3 quick questions on this:
1. Assuming the logic looks fine to you, can you clarify which test classes I need to update? (So far I found `SchemaGeneratorConfigBuilderTest.java`).
2. Do I need to update the github.io documentation you have published on the gh-pages branch?
3. Is it worthwhile to add an example within jsonschema-examples demonstrating the customization of the ObjectMapper to print yaml?

feat: add `withObjectMapper` method to customize serialization of schemas to file

---

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/ValidationErrorMessageExample.java
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/ValidationErrorMessageExample-result.json

As requested in #373, show-casing possibility of schema manipulation in order to include validation messages in non-standard `"message"` property. The example is not intended to cover the complete annotation support included in the `JakartaValidationModule`.
As this is not part of the official JSON Schema, whether or not the messages are included as expected is unclear.
Additional challenge: there is often not a one-to-one match being Java validation annotation and the corresponding JSON Schema keyword.
The example is based on the `JakartaValidationModule` but a solution involving the `JavaxValidationModule` would be based on the same principles.

chore: add example for validation messages

---

jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModule.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorSimpleTypesTest.java
slate-docs/source/includes/_main-generator-options.md

feat: support the "format" standard built-in tags (without the OpenAPI ones)

---

jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java

Targeting:
- `SchemaCleanUpUtils`
- `AttributeCollector`

chore: refactor to improve code health

---

checkstyle.xml
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/Util.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/GlobHandler.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/GlobHandlerTest.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java

Targeting:
- `SchemaGeneratorMojo` (Maven plugin)

chore: further refactoring for code health improvement

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorCustomDefinitionsTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_2019_09.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_2020_12.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_6.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_7.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testenum-FULL_DOCUMENTATION-default.json
slate-docs/source/includes/_main-generator-options.md

Created in response to https://github.com/victools/jsonschema-generator/discussions/410.

feat: option to inline nullable schemas

---

jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_2019_09.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_2020_12.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_6.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/circular-custom-definition-DRAFT_7.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-NO_SUBTYPES.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-ONE_SUBTYPE_INVALID.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-ONE_SUBTYPE_VALID.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-THREE_SUBTYPES.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass-withsupertypereferences-TWO_SUBTYPES.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION-typeattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-FULL_DOCUMENTATION.json

When using `Option.DEFINITIONS_FOR_ALL_SCHEMAS` and the new `Option.INLINE_NULLABLE_SCHEMAS`, while all references to a given type are nullable, no non-nullable definition is being created.
Fixing that here, with the result that some expected unit test results changed in https://github.com/victools/jsonschema-generator/pull/412 are being reverted again to their previous behavior.

fix: respect definitions for all when inlining nullable references

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/OptionPreset.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/Util.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/AbstractTypeAwareTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorMemberCleanUpTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/AttributeCollectorTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/naming/SchemaDefinitionNamingStrategyTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/AbstractTypeAwareTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/CustomEnumDefinitionProviderTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/TestType.java
jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/TestType.java
jsonschema-module-javax-validation/src/test/java/com/github/victools/jsonschema/module/javax/validation/TestType.java
jsonschema-module-swagger-1.5/src/test/java/com/github/victools/jsonschema/module/swagger15/TestType.java

Introduce `Option.DUPLICATE_MEMBER_ATTRIBUTE_CLEANUP_AT_THE_END` for discarding attributes contained both in property/member schemas and the common definitions being referenced from the same property/member schema.
Closes #420.

feat: Support removal of duplicate attributes from member schemas

---

jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonUnwrappedDefinitionProvider.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IntegrationTest.java
jsonschema-module-jackson/src/test/resources/com/github/victools/jsonschema/module/jackson/integration-test-result.json

Members with the `@JsonUnwrapped` annotation were being completely dropped when inherited from a super-class or interface.
This PR fixes the `@JsonUnwrapped` lookup to use `ResolvedMember` instead of `RawMember` so that it would now consider inherited members. I added a concrete example of how this should work to the `IntegrationTest`.

Fix Jackson JsonUnwrapped to consider inherited members

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/FlattenedWrapperModule.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/SimpleTypeModule.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorCustomDefinitionsTest.java

Change in response to #440.
When a custom property definition is provided for a `void` method, it is now being considered and applied.

feat: extend support for void methods

---

jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
jsonschema-module-jakarta-validation/README.md
jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java
jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/IntegrationTest.java
jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModuleTest.java
jsonschema-module-jakarta-validation/src/test/resources/com/github/victools/jsonschema/module/jakarta/validation/integration-test-result.json
slate-docs/source/includes/_jakarta-validation-module.md

Set `enum`/`const` based on the presence of Jakarta `@AssertTrue` and/or `@AssertFalse`.
See https://github.com/victools/jsonschema-generator/issues/455#issuecomment-2221494969 for background info.

Populate enum/const from Jakarta AssertTrue and/or AssertFalse annotations

---

CHANGELOG.md
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/SingleArrayItemExample.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/module/SingleValueAsArrayModule.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorComplexTypesTest.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass1-JAVA_OBJECT-methodattributes.json
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
slate-docs/source/includes/_main-generator-options.md

Adding new `Option.ACCEPT_SINGLE_VALUE_AS_ARRAY` to support the behavior of Jackson's ` DeserializationFeature.ACCEPT_SINGLE_VALUE_AS_ARRAY` in the generated schema.
Resolves #458.

feat: Introduce Option.ACCEPT_SINGLE_VALUE_AS_ARRAY

---

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/DependentRequiredExample.java
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/DependentRequiredExample-result.json
slate-docs/source/includes/_main-generator-individual.md

As requested in the issue, I'm adding a complete version of the provided example for configuring the `"dependentRequired"` keyword.
Resolves #463.

chore(docs): add example for dependentRequired usage

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/CustomEnumDefinitionProvider.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonIdentityReferenceDefinitionProvider.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonUnwrappedDefinitionProvider.java

fix: npe for custom void definition

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/MemberCollectionContextImpl.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IgnorePropertyTest.java

feat: include property name override before ignore check

---

CHANGELOG.md
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/Option.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaBuilder.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/SchemaGeneratorConfig.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/test/resources/com/github/victools/jsonschema/generator/testclass3-JAVA_OBJECT-methodattributes.json
slate-docs/source/includes/_main-generator-options.md

Fixes #482.
Introducing new `Option.NULLABLE_ALWAYS_AS_ANYOF` that avoids the `"null"` type being included with other type values, e.g. `"type": ["object", "null"]`

feat: Enable special null type handling

---

jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtilsTest.java

When performing `allOf` clean-up, avoid duplicate entries in `allOf` and `required` arrays.
Fixes #499.

fix: Avoid duplicate items in allOf and required arrays

---

jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/NamingStrategyExample.java
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-examples/src/test/resources/com/github/victools/jsonschema/examples/NamingStrategyExample-result.json

Answering #505
Showing both:
- altering the definition name by removing an unwanted suffix
- manually ensuring uniqueness in case of name clashes, e.g., when there is a `Book` and `BookModel`, both represented as `Book`. By default, they would be `Book-1` and `Book-2`. In this example, they end up as `Book-A` and `Book-B`.

chore: add example for definition naming strategy

---

.github/workflows/codeql-analysis.yml
.github/workflows/maven.yml
jsonschema-examples/src/test/java/com/github/victools/jsonschema/examples/ExampleTest.java
jsonschema-generator-bom/pom.xml
jsonschema-generator-parent/pom.xml
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/MethodScope.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/TypeContext.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/AttributeCollector.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaCleanUpUtils.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImpl.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/impl/SchemaGeneratorConfigImpl.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorAllOfCleanUpTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/SchemaGenerationContextImplTest.java
jsonschema-maven-plugin/pom.xml
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojo.java
jsonschema-maven-plugin/src/test/java/com/github/victools/jsonschema/plugin/maven/SchemaGeneratorMojoTest.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonPropertySorter.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolver.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JsonUnwrappedDefinitionProvider.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonSubTypesResolverCustomDefinitionsTest.java
jsonschema-module-swagger-2/src/main/java/com/github/victools/jsonschema/module/swagger2/Swagger2Module.java
pom.xml

try to build with JDK17 since it's LTS version and widely used in organizations

#438 Upgrade to support jdk17

---

CHANGELOG.md
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/AnnotationInheritanceExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/EnumMapExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/JacksonDescriptionAsTitleExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/SchemaGenerationExampleInterface.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/SingleArrayItemExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/SubtypeLookUpExample.java
jsonschema-examples/src/main/java/com/github/victools/jsonschema/examples/TargetTypeOverrideExample.java
jsonschema-generator/src/main/java/com/github/victools/jsonschema/generator/FieldScope.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/AbstractTypeAwareTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/AnnotationHelperTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorCustomDefinitionsTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/SchemaGeneratorMemberCleanUpTest.java
jsonschema-generator/src/test/java/com/github/victools/jsonschema/generator/impl/module/EnumModuleTest.java
jsonschema-maven-plugin/src/main/java/com/github/victools/jsonschema/plugin/maven/GlobHandler.java
jsonschema-module-jackson/src/main/java/com/github/victools/jsonschema/module/jackson/JacksonModule.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/AbstractTypeAwareTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/IntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JacksonModuleTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/JsonPropertySorterIntegrationTest.java
jsonschema-module-jackson/src/test/java/com/github/victools/jsonschema/module/jackson/TestType.java
jsonschema-module-jakarta-validation/src/main/java/com/github/victools/jsonschema/module/jakarta/validation/JakartaValidationModule.java
jsonschema-module-jakarta-validation/src/test/java/com/github/victools/jsonschema/module/jakarta/validation/TestType.java
jsonschema-module-javax-validation/src/test/java/com/github/victools/jsonschema/module/javax/validation/TestType.java
jsonschema-module-swagger-1.5/src/test/java/com/github/victools/jsonschema/module/swagger15/TestType.java
jsonschema-module-swagger-2/src/test/java/com/github/victools/jsonschema/module/swagger2/IntegrationTest.java

Apparently, the `@JsonPropertyDescription` look-up was missed when support for the `@JacksonAnnotationsInside` on the `JacksonModule` was introduced.
Closes #521

fix: support JsonPropertyDescription annotation through JacksonAnnotationsInside combo annotation
